### ISSUE TITLE
Invisibles hard to see

### ISSUE THREAD

**Issue by surrealroad** [ifcanduela/batman-syntax#2]
If I toggle on Window Show Invisibles, they are very faint

**Comment by ifcanduela** [comment]
Hi,

this is by design and I like it that way :P, so I'm not going to change it.

You can override it yourself very easily, though. Put this in your user stylesheet (The _Stylesheet..._ entry in the _File_ menu):

``` css
atom-text-editor::shadow .invisible-character {
    color: #888 !important;
}
```

Just change `#888` to whatever color you find best.
